# Generated by Django 3.0.3 on 2020-05-07 19:33

import Apps.Usuarios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20200422_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Apps.Usuarios.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False),
        ),
    ]
