# Generated by Django 3.0.3 on 2020-03-24 02:58

import Apps.Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=30)),
                ('is_premium', models.BooleanField(default=0)),
                ('fechaNacimiento', models.DateField()),
                ('pais', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to=Apps.Usuarios.models.image_Path_User)),
                ('is_artist', models.BooleanField(default=0)),
            ],
        ),
    ]
