# Generated by Django 3.0.3 on 2020-05-07 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20200507_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(default=1, upload_to='alguma', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
            preserve_default=False,
        ),
    ]
