# Generated by Django 3.0.3 on 2020-03-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_disquera_genero_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duracion',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
