# Generated by Django 3.0.3 on 2020-03-24 20:09

import Apps.Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20200324_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disquera',
            name='duracion',
        ),
        migrations.AddField(
            model_name='disquera',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to=Apps.Usuarios.models.image_Path_User),
        ),
    ]
