# Generated by Django 3.0.3 on 2020-03-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20200324_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Disquera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Disquera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='Genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
