# Generated by Django 3.0.3 on 2020-03-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_usuariocanciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='disquera',
            options={'verbose_name': 'Disquera', 'verbose_name_plural': 'Disqueras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlist'},
        ),
        migrations.AlterModelOptions(
            name='playlistcanciones',
            options={'verbose_name': 'PlaylistCanciones', 'verbose_name_plural': 'Playlist/Canciones'},
        ),
        migrations.AlterModelOptions(
            name='usuariocanciones',
            options={'verbose_name': 'UsuarioCanciones', 'verbose_name_plural': 'Usuarios/Canciones'},
        ),
        migrations.AlterField(
            model_name='disquera',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
